make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C /home/mlenders/Repositories/RIOT-OS/RIOT.ssh/tests/gnrc_sock_dns test
make[1]: Nothing to be done for 'all'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 482, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mlenders/Repositories/RIOT-OS/RIOT.ssh/tests/gnrc_sock_dns/tests/01-run.py", line 318, in <module>
    sys.exit(run(testfunc, timeout=1, echo=False))
  File "/home/mlenders/Repositories/RIOT-OS/RIOT.ssh/dist/pythonlibs/testrunner/__init__.py", line 28, in run
    logfile=sys.stdout if echo else None)
  File "/home/mlenders/Repositories/RIOT-OS/RIOT.ssh/dist/pythonlibs/testrunner/spawn.py", line 88, in setup_child
    sync_child(child, env)
  File "/home/mlenders/Repositories/RIOT-OS/RIOT.ssh/dist/pythonlibs/testrunner/spawn.py", line 123, in sync_child
    TEST_INTERACTIVE_DELAY)
  File "/home/mlenders/Repositories/RIOT-OS/RIOT.ssh/dist/pythonlibs/testrunner/utils.py", line 41, in test_utils_interactive_sync_shell
    _test_utils_interactive_sync(child, retries, delay, '\n', '>')
  File "/home/mlenders/Repositories/RIOT-OS/RIOT.ssh/dist/pythonlibs/testrunner/utils.py", line 22, in _test_utils_interactive_sync
    child.expect_exact(ready_exp, timeout=0)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 418, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f234323cb90>
command: /usr/bin/make
args: [b'/usr/bin/make', b'cleanterm']
buffer (last 100 chars): 'rry, try again.\r\n[sudo] password for mlenders: \r\nSorry, try again.\r\n[sudo] password for mlenders: \r\n'
before (last 100 chars): 'rry, try again.\r\n[sudo] password for mlenders: \r\nSorry, try again.\r\n[sudo] password for mlenders: \r\n'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 21776
child_fd: 5
closed: False
timeout: 1
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: '>'
make: *** [/home/mlenders/Repositories/RIOT-OS/RIOT.ssh/tests/gnrc_sock_dns/../../Makefile.include:770: test] Error 1

Return value: 2
